version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: 'mongodb://mongodb:27017/candidate'
      OPENAI_API_KEY: 'sk-lh-eagleeye-P9D0Dd8KASpnoMUn509jT3BlbkFJUKxrqYFvAgDePMzY4IkD'


  mongodb:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
