version: '3.8'

services:
 nodejs:
 build:
 ports:
  - '3000:3000'
environment:
  - MONGODB_URI=mongodb://localhost:27017/
  - OPENAI_API_KEY=sk-lh-eagleeye-P9D0Dd8KASpnoMUn509jT3BlbkFJUKxrqYFvAgDePMzY4IkD
depend_on:
  - mongodb

mongodb:
  image: mongo:latest
  ports:
  - '27017:27017'